name: lua_dardo_co
description: A Lua virtual machine from lua_dardo, coroutine added.
version: 0.0.4
homepage: https://github.com/shanlihou/LuaDardo.git

environment:
  sdk: ^3.0.0

dependencies:
  sprintf: ^6.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.12
