name: lua_dardo
description: A Lua virtual machine written in Dart, which implements Lua5.3 version.
version: 0.0.11
homepage: https://github.com/arcticfox1919/LuaDardo.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sprintf: ^7.0.0
  #universal_io: ^2.2.2

dev_dependencies:
  test: ^1.17.12
  flutter_lints: ^5.0.0
